import fs from 'fs';
import path from 'path';
import { config } from '../config';
import { Logger } from '../utils/logger';
import { StorageProvider } from '../storage/storage-provider';

const logger = new Logger('YouTubeUploadService');

export interface YouTubeUploadOptions {
  title: string;
  description?: string;
  tags?: string[];
  categoryId?: string;
  privacyStatus?: 'public' | 'unlisted' | 'private';
  madeForKids?: boolean;
  notifySubscribers?: boolean;
}

export interface YouTubeUploadResult {
  videoId: string;
  url: string;
}

const YOUTUBE_UPLOAD_URL = 'https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status';

/**
 * Server-side upload to YouTube via the YouTube Data API v3 resumable upload
 * protocol.
 *
 * NOTE: To use this you must configure Google Cloud OAuth 2.0 credentials:
 *   - YOUTUBE_CLIENT_ID / YOUTUBE_CLIENT_SECRET
 *   - An OAuth refresh token for the target channel (obtained after the user
 *     authorizes your app with the youtube.upload scope).
 *
 * The provided `accessToken` is expected to be a fresh short-lived access
 * token obtained by your authorization flow. When no access token is given we
 * attempt to refresh it from YOUTUBE_REFRESH_TOKEN.
 */
export class YouTubeUploadService {
  constructor(private storage: StorageProvider) {}

  private assertConfigured() {
    if (!config.youtubeApiKey && (!config.youtubeClientId || !config.youtubeClientSecret)) {
      throw new Error(
        'YouTube upload is not configured. Set YOUTUBE_CLIENT_ID, YOUTUBE_CLIENT_SECRET ' +
        'and provide an access token (or YOUTUBE_REFRESH_TOKEN) in the backend environment.'
      );
    }
  }

  private async getAccessToken(refreshToken?: string): Promise<string> {
    // If a refresh token flow is configured, refresh here.
    if (refreshToken && config.youtubeClientId && config.youtubeClientSecret) {
      try {
        const res = await fetch('https://oauth2.googleapis.com/token', {
          method: 'POST',
          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
          body: new URLSearchParams({
            client_id: config.youtubeClientId,
            client_secret: config.youtubeClientSecret,
            refresh_token: refreshToken,
            grant_type: 'refresh_token',
          }),
        });
        const data: any = await res.json();
        if (!res.ok || !data.access_token) {
          throw new Error(data.error_description || 'Failed to refresh YouTube access token');
        }
        return data.access_token;
      } catch (e: any) {
        logger.error('Token refresh failed', e);
        throw new Error('Failed to refresh YouTube access token.');
      }
    }

    throw new Error('YouTube upload requires an authorized access token.');
  }

  /**
   * Upload a video file (by storage key) to the authenticated YouTube channel.
   * Uses the resumable upload protocol.
   */
  async uploadFile(
    storageKey: string,
    options: YouTubeUploadOptions,
    accessToken?: string,
    refreshToken?: string
  ): Promise<YouTubeUploadResult> {
    this.assertConfigured();

    const token = accessToken || (await this.getAccessToken(refreshToken));

    const filePath = this.storage.getPath(storageKey);
    const fileStats = await fs.promises.stat(filePath);
    const mimeType = 'video/mp4';

    const metadata = {
      snippet: {
        title: options.title.slice(0, 100),
        description: (options.description || 'Generated by ShortClip').slice(0, 5000),
        tags: (options.tags || []).slice(0, 500),
        categoryId: options.categoryId || '22',
        defaultLanguage: 'en',
      },
      status: {
        privacyStatus: options.privacyStatus || 'private',
        selfDeclaredMadeForKids: !!options.madeForKids,
        notifySubscribers: options.notifySubscribers ?? false,
      },
    };

    // Step 1: Initiate resumable session
    const initRes = await fetch(YOUTUBE_UPLOAD_URL, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json; charset=UTF-8',
        'X-Upload-Content-Length': fileStats.size.toString(),
        'X-Upload-Content-Type': mimeType,
      },
      body: JSON.stringify(metadata),
    });

    if (!initRes.ok) {
      const body = await initRes.text();
      logger.error('YouTube init failed', { status: initRes.status, body });
      throw new Error(this.extractApiError(body) || 'Failed to initialize YouTube upload.');
    }

    const uploadUrl = initRes.headers.get('location');
    if (!uploadUrl) {
      throw new Error('YouTube did not return an upload URL.');
    }

    // Step 2: Stream the file to the upload URL
    const uploadRes = await fetch(uploadUrl, {
      method: 'PUT',
      headers: {
        'Content-Type': mimeType,
        'Content-Length': fileStats.size.toString(),
      },
      body: this.storage.getStream(storageKey) as any,
      duplex: 'half',
    });

    if (!uploadRes.ok) {
      const body = await uploadRes.text();
      logger.error('YouTube upload failed', { status: uploadRes.status, body });
      throw new Error(this.extractApiError(body) || 'YouTube upload failed.');
    }

    const result: any = await uploadRes.json().catch(() => null);
    const videoId = result?.id || '';

    logger.info('YouTube upload complete', {
      videoId,
      file: storageKey,
      status: options.privacyStatus || 'private',
    });

    return {
      videoId,
      url: videoId ? `https://www.youtube.com/watch?v=${videoId}` : '',
    };
  }

  private extractApiError(body: string): string {
    try {
      const parsed = JSON.parse(body);
      const error = parsed?.error?.errors?.[0];
      if (error && error.message) {
        return error.reason ? `${error.reason}: ${error.message}` : error.message;
      }
      return parsed?.error?.message || '';
    } catch {
      return body.slice(0, 300);
    }
  }
}
